### ISSUE TITLE
incorrect mdi: battery icon mobile app <10%

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/companion.home-assistant#206]
this issue is still on, was reported before, but not solved yet Ha 106.6, latest mobile-app

<img width="404" alt="Schermafbeelding 2020-03-20 om 17 20 29" src="https://user-images.githubusercontent.com/33354141/77183999-6f854180-6acf-11ea-9e9b-375feec798a8.png">

incorrect mdi: icons showing no icon

<img width="426" alt="Schermafbeelding 2020-03-20 om 17 20 06" src="https://user-images.githubusercontent.com/33354141/77184063-862b9880-6acf-11ea-866e-3e48f1fbcd01.png">

please have another look? thanks!

**Comment by dshokouhi** [comment]
This is the mobile apps docs repo, I don't think this bug is filed in the correct spot.  Is this impacting android or iOS or both?

I think Android is doing this correctly? https://github.com/home-assistant/home-assistant-android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt#L75

**Comment by Mariusthvdb** [comment]
really sorry, this is supposed to be filed in the iOS mobile app repo.... please give me the correct link?

**Comment by dshokouhi** [comment]
https://github.com/home-assistant/home-assistant-ios
