### ISSUE TITLE
Favorite Entities never show on WearOS watch (Pixel watch)

### ISSUE THREAD

**Issue by x046866x** [home-assistant/companion.home-assistant#937]
I used to have some entities show up on the Home Assistant tile but they went away about 2 weeks ago.  I've since gone in to the HA application on my phone and check all the configurations but regardless of which entities I choose as Favorites the watch still gives me the message "Choose entities in settings".

The "Assist" voice activated tile worked for a day or two but I think I screwed that up in removing and re-installing the app on my watch.

Thoughts?

**Comment by dshokouhi** [comment]
This issue is not in the correct location, please open a new issue in the android repo and fill out the issue template completely so we can help you properly

https://github.com/home-assistant/android/issues/new?assignees=&labels=bug&template=Bug_report.md&title=

Also favorite entities are not added to the tile, you need to add entities in the tile settings itself.

https://companion.home-assistant.io/docs/wear-os/#tiles
